-- #877 PR-2: this file used to fill the entity identity store on every boot.
--
-- It must stay (it has run on staging, and a migration is never renamed) but it does
-- nothing now. Running the backfill here held llm-service's boot for 34 s on staging
-- (2026-09-17 05:35), past the container healthcheck, and failed the v0.0.80 rollout.
-- Boot migrations are schema only.
--
-- The backfill's definitions (staging.entity_backfill_plan, staging.entity_backfill())
-- are in 20260917T0604_datahub_entity_backfill_job.sql, and the Dagster job
-- `entity_identity_backfill` (data_engine.lanes.entity_identity) runs them, launched by
-- its sensor or by hand. Nothing in this file may read or write data.
