/**
 * #469: twin-parity conformance, TypeScript half (against a real local
 * Postgres; skips gracefully without one, throws when armed — ci-web provides
 * the database and TRUEALPHA_REQUIRE_RUNTIME=1).
 *
 * Seeds the shared cases from libs/contracts/conformance/strategy_run_parity.json
 * and asserts MartStrategyRunRepository's serialized output deep-equals the
 * frozen canon generated by the Python shipping consumer — two languages, one
 * schema, one expected byte shape. Divergence triggers (a run under a
 * non-default key, rank = 0, target_weight = 1.5) must come back
 * schema_mismatch exactly like the Python twin.
 *
 * Everything runs inside ONE transaction on the test's own client, lent to the
 * repository via db.ts's `__setTestClient` seam and rolled back at the end —
 * nothing is committed, so the fixed far-future `executed_at` can never poison
 * other tests' "latest run" isolation on a shared database.
 * Run standalone: `bun run tests/strategy-run-parity-conformance.test.ts`.
 */

import { readFileSync } from "node:fs";

import { Client, type PoolClient } from "pg";

import { __setTestClient } from "../src/server/mart/db";
import { MartStrategyRunRepository } from "../src/server/mart/strategy-run-repository";
import type { AccessContext } from "../src/contracts/strategyRun";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

const REQUIRE_DB = Boolean(process.env.DATABASE_URL || process.env.TRUEALPHA_REQUIRE_RUNTIME);
process.env.DATABASE_URL ??= "postgresql://postgres:postgres@localhost:5432/truealpha";
const DATABASE_URL = process.env.DATABASE_URL;

const FIXTURE = JSON.parse(
  readFileSync(new URL("../../../libs/contracts/conformance/strategy_run_parity.json", import.meta.url), "utf8"),
) as Record<
  string,
  {
    run: Record<string, unknown>;
    decisions: Record<string, unknown>[];
    request_strategy_id: string;
    expected_report?: Record<string, unknown>;
    expected_reason?: string;
  }
>;

const CONTEXT: AccessContext = {
  contextId: "ctx:parity",
  principalId: "principal:parity",
  tenantId: "tenant:parity",
  sessionId: "session:parity",
  authenticationMethod: "service_identity",
  issuedAt: "2026-07-23T00:00:00Z",
  expiresAt: "2026-07-23T01:00:00Z",
};

const RUN_SQL = `insert into mart.strategy_runs
 (strategy_run_id, content_sha256, strategy_key, strategy_version, definition_content_sha256,
  corpus_sha256, claim_ceiling, executed_at)
 values ($1, $2, $3, $4, $5, $6, $7, $8)
 `;

const DECISION_SQL = `insert into mart.strategy_decisions
 (strategy_decision_id, content_sha256, strategy_run_id, issuer_id, cutoff_at,
  capital_adjusted_labor_efficiency, tier, current_price_to_sales, target_price_to_sales,
  valuation_gap, eligible, outcome, exclusion_reason, rank, target_weight)
 values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
 `;

/** Stable stringify (sorted keys) so a mismatch prints one comparable line. */
function canonical(value: unknown): string {
  return JSON.stringify(value, (_key, v: unknown) =>
    v !== null && typeof v === "object" && !Array.isArray(v)
      ? Object.fromEntries(Object.entries(v as Record<string, unknown>).sort(([a], [b]) => (a < b ? -1 : 1)))
      : v,
  );
}

async function reachable(): Promise<Client | null> {
  const client = new Client({ connectionString: DATABASE_URL, connectionTimeoutMillis: 3000 });
  try {
    await client.connect();
    return client;
  } catch (error) {
    await client.end().catch(() => {});
    if (REQUIRE_DB) throw new Error(`configured Postgres is unreachable: ${String(error)}`);
    console.log("strategy-run-parity-conformance: no local Postgres and TRUEALPHA_REQUIRE_RUNTIME unset — SKIP");
    return null;
  }
}

const admin = await reachable();
if (admin !== null) {
  try {
    await admin.query("begin");
    __setTestClient(admin as unknown as Pick<PoolClient, "query">);
    for (const testCase of Object.values(FIXTURE)) {
      const r = testCase.run;
      await admin.query(RUN_SQL, [
        r.strategy_run_id,
        r.content_sha256,
        r.strategy_key,
        r.strategy_version,
        r.definition_content_sha256,
        r.corpus_sha256,
        r.claim_ceiling,
        r.executed_at,
      ]);
      for (const d of testCase.decisions) {
        await admin.query(DECISION_SQL, [
          d.strategy_decision_id,
          d.content_sha256,
          r.strategy_run_id,
          d.issuer_id,
          d.cutoff_at,
          d.capital_adjusted_labor_efficiency,
          d.tier,
          d.current_price_to_sales,
          d.target_price_to_sales,
          d.valuation_gap,
          d.eligible,
          d.outcome,
          d.exclusion_reason,
          d.rank,
          d.target_weight,
        ]);
      }
    }

    const repository = new MartStrategyRunRepository();

    const reportCase = FIXTURE.report;
    const report = await repository.getLatest(reportCase.request_strategy_id, CONTEXT);
    assert("decisions" in report, `report case: expected a report, got ${JSON.stringify(report)}`);
    // strategy_run_id/executed_at are the TS-only #370 extension; the shared
    // contract surface is what must match the Python twin byte-for-byte.
    const { strategy_run_id: _runId, executed_at: _executedAt, ...shared } = report;
    assert(
      canonical(shared) === canonical(reportCase.expected_report),
      `report serialization diverges from the frozen canon:\n  ts:     ${canonical(shared)}\n  canon:  ${canonical(reportCase.expected_report)}`,
    );

    for (const name of ["wrong_strategy_id", "rank_zero", "weight_out_of_bounds"] as const) {
      const divergence = FIXTURE[name];
      const result = await repository.getLatest(divergence.request_strategy_id, CONTEXT);
      assert(!("decisions" in result), `${name}: expected unavailable, got a report`);
      assert(
        result.reason === divergence.expected_reason,
        `${name}: expected ${divergence.expected_reason}, got ${result.reason}`,
      );
    }

    console.log("#469 strategy-run twin-parity conformance passed");
  } finally {
    __setTestClient(null);
    await admin.query("rollback").catch(() => {});
    await admin.end().catch(() => {});
  }
}
