#!/bin/bash
# Prepare (or refresh) the HOST-side ingestion runtime on the VPS.
#
# The sweeps run as host processes because moomoo OpenD only listens on the
# host's 127.0.0.1; Postgres is reached through the loopback port the
# truealpha/01.postgres compose publishes (infra2: staging 15432, prod 15433),
# and MinIO through its compose bridge IP, resolved fresh on every run
# (container IPs change on recreation — rerun this script after redeploys).
#
# Reads DB password / SEC_USER_AGENT / S3 credentials out of the app
# vault-agent's rendered env — Vault stays the single source of truth and no
# secret is ever written anywhere but the gitignored .env this script owns.
#
# Idempotent. Usage (as root on the VPS):
#   bash apps/data-engine/scripts/setup_vps_ingest.sh [staging|production]
# First run: clone the repo, then run the script from the checkout:
#   git clone https://github.com/wangzitian0/truealpha /data/truealpha/ingest
#   bash /data/truealpha/ingest/apps/data-engine/scripts/setup_vps_ingest.sh

set -euo pipefail

ENV_NAME="${1:-staging}"
case "$ENV_NAME" in
  production) SUFFIX="" ;;
  staging)    SUFFIX="-staging" ;;
  *) echo "unsupported env: $ENV_NAME" >&2; exit 1 ;;
esac

REPO_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
AGENT="truealpha-app-vault-agent${SUFFIX}"
MINIO="platform-minio${SUFFIX}"
echo "== repo: $REPO_DIR  env: $ENV_NAME"

echo "== uv"
export PATH="$HOME/.local/bin:$PATH"
if ! command -v uv >/dev/null 2>&1; then
  # Deliberately NOT curl|sh here: this script runs as root on the VPS, and
  # piping a remote installer into a root shell is a supply-chain hole. Install
  # once, explicitly, from a pinned release you can inspect:
  echo "uv is not installed. Install a pinned release first, e.g.:" >&2
  echo '  curl -LsSfO https://github.com/astral-sh/uv/releases/download/0.9.26/uv-installer.sh' >&2
  echo "  less uv-installer.sh   # inspect, then: sh uv-installer.sh" >&2
  exit 1
fi
uv --version

echo "== python deps"
cd "$REPO_DIR"
uv sync --all-packages >/dev/null && echo synced

echo "== migrations -> truealpha-postgres${SUFFIX} (idempotent)"
for f in db/migrations/*.sql db/roles.sql; do
  echo "   $f"
  docker exec -i "truealpha-postgres${SUFFIX}" psql -U postgres -d truealpha -v ON_ERROR_STOP=1 -q < "$f"
done

echo "== derive .env from the vault-rendered app env"
# The compose publishes postgres on a host-loopback port (fixed per env once
# infra2's TA_POSTGRES_HOST_PORT injection is live; ephemeral otherwise) —
# read whatever is actually published instead of assuming the number.
PG_PORT=$(docker port "truealpha-postgres${SUFFIX}" 5432/tcp 2>/dev/null | head -1 | awk -F: "{print \$NF}")
[ -n "$PG_PORT" ] || { echo "truealpha-postgres${SUFFIX} publishes no host port — deploy the 01.postgres compose with the ports mapping first" >&2; exit 1; }
echo "   postgres host port: $PG_PORT"
RENDERED=$(docker exec "$AGENT" cat /vault/secrets/.env)
get() { echo "$RENDERED" | grep "^$1=" | head -1 | cut -d= -f2- | tr -d '"'; }
# Both postgresql:// and postgres:// are valid (RuntimeSettings accepts either)
# and the username is whatever the URL says — assume neither.
DB_URL=$(get DATABASE_URL)
PG_USER=$(echo "$DB_URL" | sed -nE 's|^postgres(ql)?://([^:/@]+):.*|\2|p')
PG_PASSWORD=$(echo "$DB_URL" | sed -nE 's|^postgres(ql)?://[^:/@]+:([^@]*)@.*|\2|p')
[ -n "$PG_USER" ] && [ -n "$PG_PASSWORD" ] || { echo "could not parse user/password from the rendered DATABASE_URL" >&2; exit 1; }

# MinIO: prefer a host-routable container address (fast, LAN-local). Docker
# bridge subnets are configurable, so probe EVERY address the container holds
# instead of pattern-matching ranges — the health check decides reachability
# (overlay addresses simply fail it). Fall back to the Traefik route.
S3_ENDPOINT="https://s3${SUFFIX}.zitian.party"
for ip in $(docker inspect "$MINIO" --format '{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}'); do
  if curl -sf -m 3 "http://$ip:9000/minio/health/live" >/dev/null; then
    S3_ENDPOINT="http://$ip:9000"
    break
  fi
done
echo "   S3_ENDPOINT=$S3_ENDPOINT"

umask 077
cat > "$REPO_DIR/.env" <<ENV
# Generated by setup_vps_ingest.sh ($ENV_NAME) — rerun the script to refresh.
# NEVER commit this file (gitignored); secrets come from Vault via the app agent.
APP_ENV=$ENV_NAME
DATABASE_URL=postgresql://$PG_USER:$PG_PASSWORD@127.0.0.1:$PG_PORT/truealpha
S3_ENDPOINT=$S3_ENDPOINT
S3_ACCESS_KEY=$(get S3_ACCESS_KEY)
S3_SECRET_KEY=$(get S3_SECRET_KEY)
S3_BUCKET=$(get S3_BUCKET)
S3_REGION=$(get S3_REGION)
SEC_USER_AGENT=$(get SEC_USER_AGENT)
MOOMOO_OPEND_HOST=127.0.0.1
MOOMOO_OPEND_PORT=11111
MOOMOO_LEDGER_BACKEND=postgres
MOOMOO_MONTHLY_CALL_BUDGET=20000
MOOMOO_CALLS_PER_30S=8
ENV
echo "   $REPO_DIR/.env written (mode 600)"

echo "== doctor"
uv run --package truealpha-data-engine python apps/data-engine/scripts/doctor_ingest.py
