"""Stable contracts shared by ingestion, factors, runtime, and backtests."""

from truealpha_contracts.capture import (
    CaptureCellRequirement,
    CaptureCellStatus,
    CaptureEnvironment,
    CaptureManifest,
    CaptureManifestCell,
    CaptureManifestStatus,
    CaptureRequirementLevel,
    CaptureScope,
    CaptureSubject,
    CaptureSubjectKind,
    canonical_sha256,
)
from truealpha_contracts.data_quality import (
    STRATEGY_DATA_REQUIREMENTS,
    DataDomain,
    DataQualityReport,
    EvidenceCase,
    EvidenceKind,
    QualityCheckResult,
    QualityStatus,
    ReadinessAssessment,
    ReadinessLevel,
    Strategy,
    StrategyDataRequirement,
)
from truealpha_contracts.metrics import (
    FUSION_RULESET_VERSION,
    METRICS,
    MetricSpec,
    UnitFamily,
    fusion_rank,
    source_priority,
)
from truealpha_contracts.models import (
    AnalystRatingEvent,
    AsOfQuery,
    BacktestDataset,
    DataSource,
    EntityIdentifier,
    FinancialFact,
    FundHolding,
    GraphEdge,
    PriceBar,
    RawCapture,
    RawIngestionEnvelope,
    RawObjectRef,
)
from truealpha_contracts.ports import BacktestDataGateway, PointInTimeRepository, RawObjectStore

__all__ = [
    "AnalystRatingEvent",
    "AsOfQuery",
    "BacktestDataGateway",
    "BacktestDataset",
    "CaptureCellRequirement",
    "CaptureCellStatus",
    "CaptureEnvironment",
    "CaptureManifest",
    "CaptureManifestCell",
    "CaptureManifestStatus",
    "CaptureRequirementLevel",
    "CaptureScope",
    "CaptureSubject",
    "CaptureSubjectKind",
    "canonical_sha256",
    "DataSource",
    "DataDomain",
    "DataQualityReport",
    "EvidenceCase",
    "EvidenceKind",
    "EntityIdentifier",
    "FinancialFact",
    "FundHolding",
    "FUSION_RULESET_VERSION",
    "GraphEdge",
    "METRICS",
    "MetricSpec",
    "UnitFamily",
    "fusion_rank",
    "source_priority",
    "PointInTimeRepository",
    "PriceBar",
    "RawCapture",
    "RawIngestionEnvelope",
    "RawObjectRef",
    "RawObjectStore",
    "QualityCheckResult",
    "QualityStatus",
    "ReadinessAssessment",
    "ReadinessLevel",
    "Strategy",
    "StrategyDataRequirement",
    "STRATEGY_DATA_REQUIREMENTS",
]
